stages:
- source
- binary

srpm:
  stage: source
  image: fedora:38
  before_script:
  # Fedora decided that restricting mirrors don't exist :-/
  - sed -i -e 's,^metalink=.*repo=fedora-.releasever.arch=.basearch$,baseurl=https://ftp.halifax.rwth-aachen.de/fedora/linux/releases/$releasever/Everything/$basearch/os/,g' /etc/yum.repos.d/fedora.repo; cat /etc/yum.repos.d/fedora.repo
  - sed -i -e 's,^metalink=.*repo=updates-released-f.releasever.arch=.basearch$,baseurl=https://ftp.halifax.rwth-aachen.de/fedora/linux/updates/$releasever/Everything/$basearch/,g' /etc/yum.repos.d/fedora-updates.repo; cat /etc/yum.repos.d/fedora-updates.repo
  - sed -i -e 's,^metalink=.*repo=fedora-modular-.releasever.arch=.basearch$,baseurl=https://ftp.halifax.rwth-aachen.de/fedora/linux/releases/$releasever/Modular/$basearch/os/,g' /etc/yum.repos.d/fedora-modular.repo; cat /etc/yum.repos.d/fedora-modular.repo
  - sed -i -e 's,^metalink=.*repo=updates-released-modular-f.releasever.arch=.basearch$,baseurl=https://ftp.halifax.rwth-aachen.de/fedora/linux/updates/$releasever/Modular/$basearch/,g' /etc/yum.repos.d/fedora-updates-modular.repo; cat /etc/yum.repos.d/fedora-updates-modular.repo
  - dnf install -y git rpm-build rpmdevtools
  - rpmdev-setuptree
  - VER=$(git describe --always | sed -e 's/-/./g')
  - mkdir -p products/tar
  - git archive --prefix=beidconnect-$VER/ -o products/tar/beidconnect-$VER.tar.gz origin/$CI_COMMIT_REF_NAME
  - cp products/tar/beidconnect-$VER.tar.gz ~/rpmbuild/SOURCES/
  - echo $VER > products/version
  - COMMIT_DATE=$(git log --date=rfc HEAD^..HEAD|grep ^Date|cut -d ' ' -f 2-|sed -e 's/^\s*//')
  - echo $COMMIT_DATE > products/date
  script:
  - rpmbuild --define "version $VER" -bs linux/beidconnect.spec
  after_script:
  - mkdir -p products/srpm
  - cp ~/rpmbuild/SRPMS/beidconnect-*.src.rpm products/srpm/
  artifacts:
    paths:
    - products
    when:
      on_success

.build:fedora: &fedbuild
  stage: binary
  image: fedora:38
  dependencies:
  - srpm
  before_script:
  # Fedora decided that restricting mirrors don't exist :-/
  - sed -i -e 's,^metalink=.*repo=fedora-.releasever.arch=.basearch$,baseurl=https://ftp.halifax.rwth-aachen.de/fedora/linux/releases/$releasever/Everything/$basearch/os/,g' /etc/yum.repos.d/fedora.repo; cat /etc/yum.repos.d/fedora.repo
  - sed -i -e 's,^metalink=.*repo=updates-released-f.releasever.arch=.basearch$,baseurl=https://ftp.halifax.rwth-aachen.de/fedora/linux/updates/$releasever/Everything/$basearch/,g' /etc/yum.repos.d/fedora-updates.repo; cat /etc/yum.repos.d/fedora-updates.repo
  - sed -i -e 's,^metalink=.*repo=fedora-modular-.releasever.arch=.basearch$,baseurl=https://ftp.halifax.rwth-aachen.de/fedora/linux/releases/$releasever/Modular/$basearch/os/,g' /etc/yum.repos.d/fedora-modular.repo; cat /etc/yum.repos.d/fedora-modular.repo
  - sed -i -e 's,^metalink=.*repo=updates-released-modular-f.releasever.arch=.basearch$,baseurl=https://ftp.halifax.rwth-aachen.de/fedora/linux/updates/$releasever/Modular/$basearch/,g' /etc/yum.repos.d/fedora-updates-modular.repo; cat /etc/yum.repos.d/fedora-updates-modular.repo
  - dnf -y install mock git rpm-build rpmdevtools
  - VER=$(cat products/version)
  - sed -i -e 's,^metalink=.*repo=fedora-.releasever.arch=.basearch$,baseurl=https://ftp.halifax.rwth-aachen.de/fedora/linux/releases/$releasever/Everything/$basearch/os/,g' /etc/mock/templates/fedora-branched.tpl
  - sed -i -e 's,^metalink=.*repo=updates-released-f.releasever.arch=.basearch$,baseurl=https://ftp.halifax.rwth-aachen.de/fedora/linux/updates/$releasever/Everything/$basearch/,g' /etc/mock/templates/fedora-branched.tpl; cat /etc/mock/templates/fedora-branched.tpl
  - sed -i -e 's,^mirrorlist=.*repo=epel-7.arch=.basearch,baseurl=https://ftp.halifax.rwth-aachen.de/fedora-epel/$releasever/$basearch/,g' /etc/mock/templates/epel-7.tpl; cat /etc/mock/templates/epel-7.tpl
  - sed -i -e 's,^mirrorlist=.*repo=epel-8.arch=.basearch,baseurl=https://ftp.halifax.rwth-aachen.de/fedora-epel/$releasever/Everything/$basearch/,g' /etc/mock/templates/epel-8.tpl; cat /etc/mock/templates/epel-8.tpl
  - sed -i -e 's,^metalink=.*repo=epel-$releasever.arch=.basearch,baseurl=https://ftp.halifax.rwth-aachen.de/fedora-epel/$releasever/Everything/$basearch/,g' /etc/mock/templates/epel-9.tpl; cat /etc/mock/templates/epel-9.tpl
  script:
  - mock --old-chroot --verbose -r $DIST-$VERSION-$ARCH --define "version $VER" --rebuild products/srpm/beidconnect-*.src.rpm --resultdir $CI_PROJECT_DIR/products/$DIST-$VERSION-$ARCH
  artifacts:
    name: "beidconnect-build-$DIST-$VERSION-$ARCH"
    paths:
    - products/$DIST-$VERSION-$ARCH
    when:
      on_success

.build:deb: &debuild
  stage: binary
  image: tianon/sbuild:latest
  dependencies:
  # We don't actually need the srpms, but we do need the version file. Although that could be done in a separate job, having them together seems easier.
  - srpm
  before_script:
  - apt-get update; apt-get -y install devscripts dpkg-dev git debhelper
  - sbuild-createchroot --arch=$ARCH $CODE /srv/chroot/$CODE $MIRROR $SCRIPT
  - VER=$(cat products/version)
  - if [ $ARCH = "i386" ]; then DASHA="-A -s"; else DASHA="--no-arch-all --no-source"; fi
  - export DASHA
  - if [ ! -z "$http_proxy" ]; then echo "Acquire::http::Proxy \"$http_proxy\";" > /srv/chroot/$CODE/etc/apt/apt.conf.d/99proxy; fi
  - ./linux/deb-cl.pl "$VER" "$CODE" "$SHORT"
  script:
  - sbuild -n $DASHA -c $CODE-$ARCH-sbuild --arch=$ARCH
  after_script:
  - mkdir -p products/deb/$CODE/$ARCH
  - dcmd cp ../*ges products/deb/$CODE/$ARCH
  artifacts:
    name: "beidconnect-build-$SHORT-$CODE-$ARCH"
    paths:
    - products/deb
    when:
      on_success

.build:ubuntu: &ubbuild
  stage: binary
  image: ubuntu:latest
  dependencies:
  # We don't actually need the srpms, but we do need the version file. Although that could be done in a separate job, having them together seems easier.
  - srpm
  before_script:
  - apt-get update; apt-get -y install devscripts dpkg-dev git debhelper zstd sbuild schroot debootstrap
  - sbuild-createchroot --arch=$ARCH $CODE /srv/chroot/$CODE $MIRROR $SCRIPT
  - VER=$(cat products/version)
  - if [ $ARCH = "i386" ]; then DASHA="-A -s"; else DASHA="--no-arch-all --no-source"; fi
  - export DASHA
  - if [ ! -z "$http_proxy" ]; then echo "Acquire::http::Proxy \"$http_proxy\";" > /srv/chroot/$CODE/etc/apt/apt.conf.d/99proxy; fi
  - ./linux/deb-cl.pl "$VER" "$CODE" "$SHORT"
  script:
  - sbuild -n $DASHA -c $CODE-$ARCH-sbuild --arch=$ARCH
  after_script:
  - mkdir -p products/deb/$CODE/$ARCH
  - dcmd cp ../*ges products/deb/$CODE/$ARCH
  artifacts:
    name: "beidconnect-build-$SHORT-$CODE-$ARCH"
    paths:
    - products/deb
    when:
      on_success

build:fedora-38-64:
  <<: *fedbuild
  variables:
    VERSION: 38
    ARCH: x86_64
    DIST: fedora

build:fedora-38-32:
  <<: *fedbuild
  variables:
    VERSION: 38
    ARCH: i386
    DIST: fedora

build:fedora-39-64:
  <<: *fedbuild
  variables:
    VERSION: 39
    ARCH: x86_64
    DIST: fedora

build:fedora-39-32:
  <<: *fedbuild
  variables:
    VERSION: 39
    ARCH: i386
    DIST: fedora

bbuild:fedora-40-64:
  <<: *fedbuild
  variables:
    VERSION: 40
    ARCH: x86_64
    DIST: fedora

build:fedora-40-32:
  <<: *fedbuild
  variables:
    VERSION: 40
    ARCH: i386
    DIST: fedora

uild:centos-stream-9-64:
  <<: *fedbuild
  variables:
    VERSION: 9
    ARCH: x86_64
    DIST: centos-stream

build:centos-7-64:
  <<: *fedbuild
  variables:
    VERSION: 7
    ARCH: x86_64
    DIST: centos

build:debian-10-32:
  <<: *debuild
  variables:
    CODE: buster
    SHORT: deb10
    ARCH: i386
    MIRROR: http://deb.debian.org/debian

build:debian-10-64:
  <<: *debuild
  variables:
    CODE: buster
    SHORT: deb10
    ARCH: amd64
    MIRROR: http://deb.debian.org/debian

build:debian-11-32:
  <<: *debuild
  variables:
    CODE: bullseye
    SHORT: deb11
    ARCH: i386
    MIRROR: http://deb.debian.org/debian

build:debian-11-64:
  <<: *debuild
  variables:
    CODE: bullseye
    SHORT: deb11
    ARCH: amd64
    MIRROR: http://deb.debian.org/debian

build:debian-12-32:
  <<: *debuild
  variables:
    CODE: bookworm
    SHORT: deb12
    ARCH: i386
    MIRROR: http://deb.debian.org/debian

build:debian-12-64:
  <<: *debuild
  variables:
    CODE: bookworm
    SHORT: deb12
    ARCH: amd64
    MIRROR: http://deb.debian.org/debian

build:ubuntu-2404-64:
  <<: *ubbuild
  variables:
    CODE: noble
    ARCH: amd64
    SHORT: u2404
    MIRROR: http://archive.ubuntu.com/ubuntu
    SCRIPT: /usr/share/debootstrap/scripts/gutsy

build:ubuntu-2404-32:
  <<: *ubbuild
  variables:
    CODE: noble
    ARCH: i386
    SHORT: u2404
    MIRROR: http://archive.ubuntu.com/ubuntu
    SCRIPT: /usr/share/debootstrap/scripts/gutsy

build:ubuntu-2204-64:
  <<: *ubbuild
  variables:
    CODE: jammy
    ARCH: amd64
    SHORT: u2204
    MIRROR: http://archive.ubuntu.com/ubuntu
    SCRIPT: /usr/share/debootstrap/scripts/gutsy

build:ubuntu-2204-32:
  <<: *ubbuild
  variables:
    CODE: jammy
    ARCH: i386
    SHORT: u2204
    MIRROR: http://archive.ubuntu.com/ubuntu
    SCRIPT: /usr/share/debootstrap/scripts/gutsy

build:ubuntu-2004-64:
  <<: *debuild
  variables:
    CODE: focal
    ARCH: amd64
    SHORT: u2004
    MIRROR: http://archive.ubuntu.com/ubuntu
    SCRIPT: /usr/share/debootstrap/scripts/gutsy

build:ubuntu-2004-32:
  <<: *debuild
  variables:
    CODE: focal
    ARCH: i386
    SHORT: u2004
    MIRROR: http://archive.ubuntu.com/ubuntu
    SCRIPT: /usr/share/debootstrap/scripts/gutsy

build:ubuntu-1804-64:
  <<: *debuild
  variables:
    CODE: bionic
    ARCH: amd64
    SHORT: u1804
    MIRROR: http://archive.ubuntu.com/ubuntu
    SCRIPT: /usr/share/debootstrap/scripts/gutsy

build:ubuntu-1804-32:
  <<: *debuild
  variables:
    CODE: bionic
    ARCH: i386
    SHORT: u1804
    MIRROR: http://archive.ubuntu.com/ubuntu
    SCRIPT: /usr/share/debootstrap/scripts/gutsy
