#!/bin/sh

#  postinstall
#  beidconnect
#
APPLICATIONPATH="$HOME/Applications"
BEIDCONNECT="$APPLICATIONPATH/BeIDConnect"

CHROME_EXTENSION_PATH="$HOME/Library/Application Support/Google/Chrome/NativeMessagingHosts"
CHROME_BETA_EXTENSION_PATH="$HOME/Library/Application Support/Google/Chrome Beta/NativeMessagingHosts"
CHROMIUM_EXTENSION_PATH="$HOME/Library/Application Support/Chromium/NativeMessagingHosts"
FIREFOX_EXTENSION_PATH="$HOME/Library/Application Support/Mozilla/NativeMessagingHosts"
EDGE_EXTENSION_PATH="$HOME/Library/Application Support/Microsoft Edge/NativeMessagingHosts"

test -e "$HOME/Library/Application Support/Google/Chrome" && mkdir "$CHROME_EXTENSION_PATH"
test -e "$HOME/Library/Application Support/Google/Chrome Beta" && mkdir "$CHROME_BETA_EXTENSION_PATH"
test -e "$HOME/Library/Application Support/Chromium" && mkdir "$CHROMIUM_EXTENSION_PATH"
test -e "$HOME/Library/Application Support/Mozilla" && mkdir "$FIREFOX_EXTENSION_PATH"
test -e "$HOME/Library/Application Support/Microsoft Edge" && mkdir "$EDGE_EXTENSION_PATH"

test -e $BEIDCONNECT && $BEIDCONNECT -setup "$APPLICATIONPATH" "$CHROME_EXTENSION_PATH" "$FIREFOX_EXTENSION_PATH"
test -e "$CHROMIUM_EXTENSION_PATH" && test -e "$CHROME_EXTENSION_PATH/be.bosa.beidconnect.json" && cp "$CHROME_EXTENSION_PATH/be.bosa.beidconnect.json" "$CHROMIUM_EXTENSION_PATH/"
test -e "$CHROME_BETA_EXTENSION_PATH" && test -e "$CHROME_EXTENSION_PATH/be.bosa.beidconnect.json" && cp "$CHROME_EXTENSION_PATH/be.bosa.beidconnect.json" "$CHROME_BETA_EXTENSION_PATH/"
test -e "$EDGE_EXTENSION_PATH" && test -e "$EDGE_EXTENSION_PATH/be.bosa.beidconnect.json" && cp "$CHROME_EXTENSION_PATH/be.bosa.beidconnect.json" "$EDGE_EXTENSION_PATH/"

exit 0
