#!/bin/sh

#  postinstall
#  eidlink
#
EIDLINKPATH="$HOME/Applications"
EIDLINK="$EIDLINKPATH/eIDLink"

CHROME_EXTENSION_PATH="$HOME/Library/Application Support/Google/Chrome/NativeMessagingHosts"
CHROMIUM_EXTENSION_PATH="$HOME/Library/Application Support/Chromium/NativeMessagingHosts"
FIREFOX_EXTENSION_PATH="$HOME/Library/Application Support/Mozilla/NativeMessagingHosts"

test -e "$HOME/Library/Application Support/Google/Chrome" && mkdir "$CHROME_EXTENSION_PATH"
test -e "$HOME/Library/Application Support/Chromium" && mkdir "$CHROMIUM_EXTENSION_PATH"
test -e "$HOME/Library/Application Support/Mozilla" && mkdir "$FIREFOX_EXTENSION_PATH"

test -e $EIDLINK && $EIDLINK -setup "$EIDLINKPATH" "$CHROME_EXTENSION_PATH" "$FIREFOX_EXTENSION_PATH"
test -e "$CHROMIUM_EXTENSION_PATH" && test -e "$CHROME_EXTENSION_PATH/be.bosa.eidlink.json" && cp "$CHROME_EXTENSION_PATH/be.bosa.eidlink.json" "$CHROMIUM_EXTENSION_PATH/"

exit 0
