#!/bin/sh

#  uninstall.sh
#  eidlink
#
EIDLINK="$HOME/Applications/eIDLink"

CHROME_EXTENSION_PATH="$HOME/Library/Application Support/Google/Chrome/NativeMessagingHosts/be.bosa.eidlink.json"
CHROMIUM_EXTENSION_PATH="$HOME/Library/Application Support/Chromium/NativeMessagingHosts/be.bosa.eidlink.json"
FIREFOX_EXTENSION_PATH="$HOME/Library/Application Support/Mozilla/NativeMessagingHosts/be.bosa.eidlink.json"

test -e "$EIDLINK" && rm -f "$EIDLINK"
test -e "$CHROME_EXTENSION_PATH" && rm -f "$CHROME_EXTENSION_PATH"
test -e "$CHROMIUM_EXTENSION_PATH" && rm -f "$CHROMIUM_EXTENSION_PATH"
test -e "$FIREFOX_EXTENSION_PATH" && rm -f "$FIREFOX_EXTENSION_PATH"


pkgutil --forget be.bosa.eidlink

exit 0
