#!/bin/sh

#  postinstall
#  beidconnect
#
BEIDCONNECT=$HOME/Applications/BeIDConnect\ Extension.app

#start BeIDConnect for user to accept in Safari
#echo "$BEIDCONNECT"
test -e "$BEIDCONNECT" && open "$BEIDCONNECT"

exit 0
