#!/bin/sh

#  postinstall
#  beidconnect
#
BEIDCONNECT=$HOME/Applications/BeIDConnect\ Extension.app

#start BeIDConnect for user to accept in Safari
#echo "$BEIDCONNECT"

for i in {1..10}
do
	test -e "$BEIDCONNECT" && open "$BEIDCONNECT" && break
	echo "waiting..." 
	sleep 1
done

exit 0

